=== davidas02/2122_LMSGI_DavidAS/ud04/04/04.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="curriculum">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string"/>
                <xs:element name="apellidos" type="xs:string"/>
                <xs:element name="anyo_nac" type="xs:gYear"/>
                <xs:element name="residencia">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ciudad" type="xs:string"/>
                            <xs:element name="pais" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="contacto">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="telefono" >
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[0-9]{9}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="email">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Za-z0-9]*[.]{1}[@]{1}[A-Za-z0-9]*[.]{1}[A-Za-z0-9]*[.]{1}[a-z]*"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="linkedin" type="xs:string"/>
                            <xs:element name="descripcion" type="xs:string"/>
                            <xs:element name="competencias">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="competencia" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="nombre" type="xs:string"/>
                                                <xs:attribute name="nivel" type="xs:string"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="formaciones">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="formacion" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="titulo" type="xs:string"/>
                                                <xs:attribute name="centro" type="xs:string"/>
                                                <xs:attribute name="anyo" type="xs:gYear"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="experiencias">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="experiencia" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="puesto" type="xs:string"/>
                                                    <xs:element name="empresa" type="xs:string" />
                                                    <xs:element name="inicio" type="xs:gYear"/>
                                                    <xs:element name="fin" type="xs:gYear" minOccurs="0"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== davidas02/2122_LMSGI_DavidAS/ud04/04/04.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE curriculum[
<!ELEMENT curriculum (nombre,apellidos,anyo_nac,residencia,contacto)>
<!ATTLIST curriculum
             xmlns:xsi CDATA #IMPLIED
             xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT anyo_nac (#PCDATA)>
<!ELEMENT residencia (ciudad,pais)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT contacto (telefono,email,linkedin,descripcion,competencias?,formaciones?,experiencias?)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT linkedin (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT competencias (competencia+)>
<!ELEMENT competencia EMPTY>
<!ATTLIST competencia nombre CDATA #REQUIRED
                      nivel (alto|medio|bajo) "medio">
<!ELEMENT formaciones (formacion+)>
<!ELEMENT formacion EMPTY>
<!ATTLIST formacion titulo CDATA #REQUIRED
                    centro CDATA #REQUIRED
                    anyo   CDATA #IMPLIED>
<!ELEMENT experiencias (experiencia+)>
<!ELEMENT experiencia (puesto,empresa,inicio,fin?)>
<!ELEMENT puesto (#PCDATA)>
<!ELEMENT empresa (#PCDATA)>
<!ELEMENT inicio (#PCDATA)>
<!ELEMENT fin (#PCDATA)>
]>
<curriculum
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='04.xsd'>
    <nombre>
        David
    </nombre>
    <apellidos>
        Aparicio Sir
    </apellidos>
    <anyo_nac>
        2002  
    </anyo_nac>
    <residencia>
        <ciudad>
            Benavente
        </ciudad>
        <pais>
            España
        </pais>
    </residencia>
    <contacto>
        <telefono>722289853</telefono>
        <email>
            david.apasir@educa.jcyl.es
        </email>
        <linkedin>
            https://es.linkedin.com/apa02
        </linkedin>
        <descripcion>
            Gran trabajador
        </descripcion>
        <competencias>
            <competencia nombre="Inglés" nivel="medio"/>
        </competencias>
        <formaciones>
            <formacion titulo="SMR" centro="IES LOS SAUCES" anyo="2020"/>
        </formaciones>
        <experiencias>
            <experiencia>
                <puesto>
                    AYTE. Cocina
                </puesto>
                <empresa>
                    Restaurante TMJ
                </empresa>
                <inicio>
                    2020
                </inicio>
            </experiencia>
        </experiencias>
    </contacto>
</curriculum>
