=== davidas02/2122_LMSGI_DavidAS/ud05/04/mapaestelar.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT mapaEstelar (constelacion,estrella)>
<!ATTLIST mapaEstelar xmlns:xsi CDATA #IMPLIED
xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
<!ELEMENT constelacion (#PCDATA|nombreEspanol|superficie|estrellas|objetos|colindantes|observacion)*>
<!ATTLIST constelacion nombreLatin CDATA #IMPLIED>
<!ELEMENT nombreEspanol (#PCDATA)>
<!ELEMENT superficie (#PCDATA)>
<!ELEMENT estrellas (asterismo,masBrillante)>
<!ATTLIST estrellas numero CDATA #REQUIRED>
<!ELEMENT asterismo (#PCDATA)>
<!ELEMENT masBrillante (nombreEstrella)>
<!ATTLIST masBrillante luminosidad CDATA "soles" >
<!ELEMENT nombreEstrella (#PCDATA)>
<!ELEMENT objetos (cumulos,nebulosas,galaxias,cuasares,lluviaDeMeteoros*)>
<!ELEMENT cumulos (#PCDATA)>
<!ELEMENT nebulosas (#PCDATA)>
<!ELEMENT galaxias (#PCDATA)>
<!ELEMENT cuasares (#PCDATA)>
<!ELEMENT lluviaDeMeteoros (#PCDATA)>
<!ELEMENT colindantes (nombre+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT observacion (hemisferio,mes,hora)>
<!ELEMENT hemisferio (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT estrella (nombre,constelacion,distancia,luminosidad,temperatura,masa)>
<!ELEMENT const (#PCDATA)>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia medida CDATA #FIXED "aÃ±os luz">
<!ELEMENT luminosidad (#PCDATA)>
<!ATTLIST luminosidad medida CDATA "soles">
<!ELEMENT temperatura (#PCDATA)>
<!ATTLIST temperatura medida CDATA "K">
<!ELEMENT masa (#PCDATA)>
<!ATTLIST masa medida CDATA "soles">

=== davidas02/2122_LMSGI_DavidAS/ud05/04/mapaestelar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapaEstelar SYSTEM "mapaestelar.dtd">
<mapaEstelar xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
xsi:noNamespaceSchemaLocation='mapaestelar.xsd'>
    <constelacion nombreLatin="Ursa Maior">
        <nombreEspanol>Osa Mayor</nombreEspanol>
        <superficie>1279.7</superficie>
        <estrellas numero="209">
            <asterismo>7</asterismo>
            <masBrillante luminosidad="1.77">
                <nombreEstrella>Alioth</nombreEstrella>
            </masBrillante>
        </estrellas>
        <objetos>
            <cumulos>false</cumulos>
            <nebulosas>true</nebulosas>
            <galaxias>true</galaxias>
            <cuasares>false</cuasares>
            <lluviaDeMeteoros>Kappa Ursa Mayóridas</lluviaDeMeteoros>
            <lluviaDeMeteoros>Lambda Ursa Mayóridas</lluviaDeMeteoros>
            <lluviaDeMeteoros>Psi Ursa Mayóridas</lluviaDeMeteoros>
            <lluviaDeMeteoros>Ursa Mayóridas de octubre</lluviaDeMeteoros>
        </objetos>
        <colindantes>
            <nombre>Bootes</nombre>
            <nombre>Camelopardalis</nombre>
            <nombre>Leo</nombre>
        </colindantes>
        <observacion>
            <hemisferio>Norte</hemisferio>
            <mes>04</mes>
            <hora>21:00:00</hora>
        </observacion>
    </constelacion>
    <estrella>
        <nombre>Alioth</nombre>
        <const>Osa Mayor</const>
        <distancia medida="años luz">81</distancia>
        <luminosidad medida="soles">108</luminosidad>
        <temperatura medida="K">9400</temperatura>
        <masa medida="soles">3</masa>
    </estrella>
</mapaEstelar>
