<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE hechos [
<!ELEMENT hechos (hecho+)>
<!ATTLIST hechos
             xmlns:xsi CDATA #IMPLIED
             xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
<!ELEMENT hecho (descripcion,fecha)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT fecha (dia,mes,anyo)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anyo (#PCDATA)>
]>
<hechos
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='03.xsd'>
    <hecho>
        <descripcion>
            Se funda Youtube
        </descripcion>
        <fecha>
            <dia>
                15
            </dia>
            <mes>
                2
            </mes>
            <anyo>
                2005
            </anyo>
        </fecha>
    </hecho>
    <hecho>
        <descripcion>
            Se funda Google
        </descripcion>
        <fecha>
            <dia>
                4
            </dia>
            <mes>
                9
            </mes>
            <anyo>
                1998
            </anyo>
        </fecha>
    </hecho>
    <hecho>
        <descripcion>
            Se funda Facebook
        </descripcion>
        <fecha>
            <dia>
                4
            </dia>
            <mes>
                2
            </mes>
            <anyo>
                2004
            </anyo>
        </fecha>
    </hecho>
</hechos>
