=== davidas02/2122_LMSGI_DavidAS/ud04/01/01.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="email">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="remitente">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                           <!-- <xs:pattern value="[a-zA-Z0-9.]{*}[@][a-zA-Z0-9]{*}[.][a-z]{*}"/>-->
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="destinatarios">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="destinatario" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="fecha" type="xs:date"/>
                <xs:element name="asunto" type="xs:string"/>
                <xs:element name="mensaje" type="xs:string"/>
                <xs:element name="ficheros">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fichero" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="type" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== davidas02/2122_LMSGI_DavidAS/ud04/01/01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE email[
   <!ELEMENT email (remitente,destinatarios,fecha,asunto,mensaje?,ficheros?)>
   <!ATTLIST email
             xmlns:xsi CDATA #IMPLIED
             xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
    <!ELEMENT remitente (#PCDATA)>
   <!ELEMENT destinatarios (destinatario+)>
   <!ELEMENT destinatario (#PCDATA)>
   <!ELEMENT fecha (#PCDATA)>
   <!ELEMENT asunto (#PCDATA)>
   <!ELEMENT mensaje (#PCDATA)>
   <!ELEMENT ficheros (fichero+)>
   <!ELEMENT fichero (nombre,type)>
   <!ELEMENT nombre (#PCDATA)>
   <!ELEMENT type (#PCDATA)>
]>
<email
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='01.xsd'>
    <remitente>
        david.apasir@educa.jcyl.es
    </remitente>
    <destinatarios>
        <destinatario>
            marodriguezn@educa.jcyl.es
        </destinatario>
        <destinatario>
            hramoso@educa.jcyl.es
        </destinatario>
    </destinatarios>
    <fecha>
        2022-01-20
    </fecha>
    <asunto>
        practicas xml
    </asunto>
    <mensaje>
        Aqui est√° la practica 01 de xml
    </mensaje>
    <ficheros>
        <fichero>
            <nombre>
                01.xml
            </nombre>
            <type>
                application/xml
            </type>
        </fichero>
        <fichero>
            <nombre>
                02.xml
            </nombre>
            <type>
                application/xml
            </type>
        </fichero>
    </ficheros>
</email>
